#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Markdown to PDF and Word Converter - Academic Edition
Converts Markdown files to PDF and Word (.docx) formats with professional academic formatting.

Features:
- Title page with document information
- Table of Contents with clickable links (PDF)
- Chinese font support (SimSun/宋体 for body text)
- Page numbers
- 1.5 line spacing
- Styled blockquotes
- Formatted bibliography
- Distinct heading sizes (H1, H2, H3)

Usage:
    python markdown-converter.py <input.md> [--output-dir OUTPUT_DIR]
    python markdown-converter.py --install-deps  # Install required packages
"""

import os
import sys
import io
import datetime

# Set UTF-8 encoding for Windows console
if sys.platform == 'win32':
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding='utf-8', errors='replace')

import argparse
from pathlib import Path
import re

try:
    import markdown
    from docx import Document
    from docx.shared import Pt, RGBColor, Inches, Cm, Mm
    from docx.enum.text import WD_ALIGN_PARAGRAPH, WD_LINE_SPACING
    from docx.oxml.ns import qn
    from docx.oxml import OxmlElement
except ImportError as e:
    missing_packages = []
    if "markdown" in str(e):
        missing_packages.append("markdown")
    if "docx" in str(e):
        missing_packages.append("python-docx")
    print(f"Error: Missing required package(s): {', '.join(missing_packages)}")
    print("Run: pip install markdown python-docx")
    sys.exit(1)


class MarkdownConverter:
    """Convert Markdown files to PDF and Word formats with academic formatting."""

    def __init__(self, input_file, output_dir=None):
        self.input_file = Path(input_file)
        self.output_dir = Path(output_dir) if output_dir else self.input_file.parent
        self.base_name = self.input_file.stem
        self.toc_entries = []  # Table of contents entries for PDF
        self.bibliography_items = []  # Bibliography items

    def read_markdown(self):
        """Read markdown file content."""
        with open(self.input_file, 'r', encoding='utf-8') as f:
            return f.read()

    def add_page_number(self, doc, page_num):
        """Add page number to document."""
        section = doc.sections[page_num]
        footer = section.footer
        paragraph = footer.paragraphs[0] if footer.paragraphs else footer.add_paragraph()
        paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = paragraph.add_run(f"- {page_num + 1} -")
        run.font.name = '宋体'
        run._element.rPr.rFonts.set(qn('w:eastAsia'), '宋体')
        run.font.size = Pt(9)

    def convert_to_word(self, content):
        """Convert markdown to Word document with academic formatting."""
        doc = Document()

        # === 设置页面格式 ===
        # A4纸张: 21cm x 29.7cm
        section = doc.sections[0]
        section.page_height = Cm(29.7)
        section.page_width = Cm(21.0)
        section.left_margin = Cm(2.54)   # 1英寸
        section.right_margin = Cm(2.54)
        section.top_margin = Cm(2.54)
        section.bottom_margin = Cm(1.91)

        # === 设置默认样式 ===
        normal_style = doc.styles['Normal']
        normal_style.font.name = '宋体'
        normal_style._element.rPr.rFonts.set(qn('w:eastAsia'), '宋体')
        normal_style.font.size = Pt(11)

        # 设置段落格式
        paragraph_format = normal_style.paragraph_format
        paragraph_format.line_spacing = 1.5
        paragraph_format.space_before = Pt(0)
        paragraph_format.space_after = Pt(0)

        # === 创建标题页 ===
        doc.add_page_break()

        # 标题居中
        title_paragraph = doc.add_paragraph()
        title_paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
        title_run = title_paragraph.add_run(self.base_name)
        title_run.font.name = '宋体'
        title_run._element.rPr.rFonts.set(qn('w:eastAsia'), '宋体')
        title_run.font.size = Pt(24)
        title_run.font.bold = True
        title_run.font.color.rgb = RGBColor(0, 0, 0)

        doc.add_paragraph()

        # 副标题/说明
        subtitle_paragraph = doc.add_paragraph()
        subtitle_paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
        subtitle_run = subtitle_paragraph.add_run("学术文献综述报告")
        subtitle_run.font.name = '宋体'
        subtitle_run._element.rPr.rFonts.set(qn('w:eastAsia'), '宋体')
        subtitle_run.font.size = Pt(16)
        subtitle_run.font.color.rgb = RGBColor(64, 64, 64)

        doc.add_paragraph()

        # 生成信息
        info_paragraph = doc.add_paragraph()
        info_paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
        date_str = datetime.datetime.now().strftime("%Y年%m月%d日")
        info_text = f"Generated by 老丁聊AI\n生成日期: {date_str}"
        info_run = info_paragraph.add_run(info_text)
        info_run.font.name = '宋体'
        info_run._element.rPr.rFonts.set(qn('w:eastAsia'), '宋体')
        info_run.font.size = Pt(10)
        info_run.font.color.rgb = RGBColor(128, 128, 128)

        # 添加分页符（新页面开始）
        doc.add_page_break()

        # === 解析Markdown内容 ===
        lines = content.split('\n')
        i = 0
        in_bibliography = False

        while i < len(lines):
            line = lines[i]

            # 检测参考文献部分
            if line.strip().startswith('##') and '参考' in line:
                in_bibliography = True
                self._add_header(doc, line[2:].strip(), level=2)
                i += 1
                continue

            # Headers
            if line.startswith('###'):
                in_bibliography = False
                self._add_header(doc, line[3:].strip(), level=3)
            elif line.startswith('##'):
                in_bibliography = False
                self._add_header(doc, line[2:].strip(), level=2)
            elif line.startswith('#'):
                in_bibliography = False
                self._add_header(doc, line[1:].strip(), level=1)

            # Blockquote (>)
            elif line.strip().startswith('>'):
                self._add_blockquote(doc, line.strip()[1:].strip())

            # Horizontal rule
            elif line.strip() == '---' or line.strip() == '***':
                doc.add_paragraph().add_run().add_tab()
                p = doc.add_paragraph()
                p.paragraph_format.border_bottom = True

            # Bold text
            elif '**' in line:
                self._add_formatted_paragraph(doc, line)

            # List items
            elif line.strip().startswith('- '):
                self._add_list_item(doc, line.strip()[2:])

            # Numbered list
            elif re.match(r'^\d+\.\s', line.strip()):
                self._add_numbered_item(doc, line.strip())

            # Table (simple detection)
            elif '|' in line and i+1 < len(lines) and '|' in lines[i+1]:
                table_lines = [line]
                i += 1
                while i < len(lines) and '|' in lines[i]:
                    table_lines.append(lines[i])
                    i += 1
                self._add_table(doc, table_lines)
                continue

            # Code block
            elif line.strip().startswith('```'):
                code_lines = []
                i += 1
                while i < len(lines) and not lines[i].strip().startswith('```'):
                    code_lines.append(lines[i])
                    i += 1
                self._add_code_block(doc, '\n'.join(code_lines))

            # Regular paragraph
            elif line.strip():
                if in_bibliography:
                    self._add_bibliography_item(doc, line.strip())
                else:
                    self._add_paragraph(doc, line)

            i += 1

        # === 添加页码 ===
        for section_idx, section in enumerate(doc.sections):
            # 为每个节添加页码（除标题页外）
            if section_idx > 0:
                self._add_page_number_to_section(section, section_idx + 1)

        # Save document
        output_path = self.output_dir / f"{self.base_name}.docx"
        doc.save(output_path)
        return output_path

    def _add_page_number_to_section(self, section, page_num):
        """Add page number to a specific section."""
        footer = section.footer
        paragraph = footer.paragraphs[0] if footer.paragraphs else footer.add_paragraph()
        paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # 添加页码域
        run = paragraph.add_run()
        fldChar1 = OxmlElement('w:fldChar')
        fldChar1.set(qn('w:fldCharType'), 'begin')

        instrText = OxmlElement('w:instrText')
        instrText.set(qn('xml:space'), 'preserve')
        instrText.text = "PAGE"

        fldChar2 = OxmlElement('w:fldChar')
        fldChar2.set(qn('w:fldCharType'), 'end')

        run._r.append(fldChar1)
        run._r.append(instrText)
        run._r.append(fldChar2)

        run.font.name = '宋体'
        run._element.rPr.rFonts.set(qn('w:eastAsia'), '宋体')
        run.font.size = Pt(9)

    def _add_header(self, doc, text, level):
        """Add a heading to document with academic formatting."""
        heading = doc.add_heading(text, level=level)
        heading.alignment = WD_ALIGN_PARAGRAPH.LEFT

        # 设置字体大小：H1=18, H2=15, H3=13
        font_sizes = {1: Pt(18), 2: Pt(15), 3: Pt(13)}
        font_size = font_sizes.get(level, Pt(12))

        # 设置标题的中文字体和大小
        for run in heading.runs:
            run.font.name = '宋体'
            run._element.rPr.rFonts.set(qn('w:eastAsia'), '宋体')
            run.font.size = font_size
            run.font.bold = True
            run.font.color.rgb = RGBColor(0, 0, 0)

        # 标题段落后间距
        heading.paragraph_format.space_before = Pt(12 if level == 1 else 10)
        heading.paragraph_format.space_after = Pt(6)

        # 添加大纲级别（用于自动目录）
        heading._element.get_or_add_pPr().get_or_add_outlineLvl().val = level - 1

    def _add_paragraph(self, doc, text):
        """Add a paragraph with basic formatting."""
        if not text.strip():
            doc.add_paragraph()
            return

        p = doc.add_paragraph()
        run = p.add_run(text)
        run.font.name = '宋体'
        run._element.rPr.rFonts.set(qn('w:eastAsia'), '宋体')
        run.font.size = Pt(11)
        run.font.color.rgb = RGBColor(0, 0, 0)

        # 设置1.5倍行距
        p.paragraph_format.line_spacing = 1.5
        p.paragraph_format.space_before = Pt(0)
        p.paragraph_format.space_after = Pt(6)

        # 处理内联格式
        if '**' in text:
            self._process_inline_formatting(text, p, run)

    def _add_blockquote(self, doc, text):
        """Add a blockquote with academic styling."""
        p = doc.add_paragraph()
        run = p.add_run(text)
        run.font.name = '宋体'
        run._element.rPr.rFonts.set(qn('w:eastAsia'), '宋体')
        run.font.size = Pt(10)
        run.font.color.rgb = RGBColor(64, 64, 64)
        run.font.italic = True

        # 缩进和边距
        p.paragraph_format.left_indent = Inches(0.75)
        p.paragraph_format.right_indent = Inches(0.25)
        p.paragraph_format.line_spacing = 1.5
        p.paragraph_format.space_before = Pt(6)
        p.paragraph_format.space_after = Pt(6)

        # 添加左边框
        pPr = p._element.get_or_add_pPr()
        pBdr = OxmlElement('w:pBdr')
        pB = OxmlElement('w:left')
        pB.set(qn('w:val'), 'single')
        pB.set(qn('w:sz'), '6')
        pB.set(qn('w:space'), '6')
        pB.set(qn('w:color'), '999999')
        pBdr.append(pB)
        pPr.append(pBdr)

    def _add_formatted_paragraph(self, doc, text):
        """Add a paragraph with bold/italic formatting."""
        p = doc.add_paragraph()
        parts = re.split(r'(\*\*[^*]+\*\*)', text)
        for part in parts:
            if part.startswith('**') and part.endswith('**'):
                run = p.add_run(part[2:-2])
                run.bold = True
            else:
                run = p.add_run(part)
            run.font.name = '宋体'
            run._element.rPr.rFonts.set(qn('w:eastAsia'), '宋体')
            run.font.size = Pt(11)
        p.paragraph_format.line_spacing = 1.5

    def _add_list_item(self, doc, text):
        """Add a bulleted list item."""
        p = doc.add_paragraph(text, style='List Bullet')
        p.paragraph_format.left_indent = Inches(0.375)
        p.paragraph_format.space_before = Pt(3)
        p.paragraph_format.space_after = Pt(3)
        for run in p.runs:
            run.font.name = '宋体'
            run._element.rPr.rFonts.set(qn('w:eastAsia'), '宋体')
            run.font.size = Pt(11)

    def _add_numbered_item(self, doc, text):
        """Add a numbered list item."""
        p = doc.add_paragraph(text, style='List Number')
        p.paragraph_format.left_indent = Inches(0.375)
        p.paragraph_format.space_before = Pt(3)
        p.paragraph_format.space_after = Pt(3)
        for run in p.runs:
            run.font.name = '宋体'
            run._element.rPr.rFonts.set(qn('w:eastAsia'), '宋体')
            run.font.size = Pt(11)

    def _add_bibliography_item(self, doc, text):
        """Add a bibliography item with hanging indent."""
        p = doc.add_paragraph()
        run = p.add_run(text)
        run.font.name = '宋体'
        run._element.rPr.rFonts.set(qn('w:eastAsia'), '宋体')
        run.font.size = Pt(10)

        # 设置悬挂缩进
        p.paragraph_format.left_indent = Inches(0.5)
        p.paragraph_format.first_line_indent = Inches(-0.5)
        p.paragraph_format.line_spacing = 1.2
        p.paragraph_format.space_before = Pt(3)
        p.paragraph_format.space_after = Pt(3)

    def _add_code_block(self, doc, code):
        """Add a code block with monospace font."""
        p = doc.add_paragraph()
        run = p.add_run(code)
        run.font.name = 'Consolas'
        run.font.size = Pt(9)
        run.font.color.rgb = RGBColor(0, 0, 0)
        p.paragraph_format.left_indent = Inches(0.5)
        p.paragraph_format.space_before = Pt(6)
        p.paragraph_format.space_after = Pt(6)

    def _add_table(self, doc, lines):
        """Add a markdown-style table with Chinese optimization."""
        # 跳过分隔符行
        rows = [l for l in lines if not re.match(r'^\s*\|[\s\-:]+\|$', l)]

        if not rows:
            return

        # 解析单元格
        table_data = []
        for row in rows:
            cells = [cell.strip() for cell in row.split('|')]
            # 移除首尾空元素
            if cells and cells[0] == '':
                cells = cells[1:]
            if cells and cells[-1] == '':
                cells = cells[:-1]
            table_data.append(cells)

        # 创建表格
        if not table_data:
            return

        num_cols = max(len(row) for row in table_data)
        table = doc.add_table(rows=len(table_data), cols=num_cols)
        table.style = 'Light Grid Accent 1'

        # 设置表格中文格式
        for row in table.rows:
            for cell in row.cells:
                for paragraph in cell.paragraphs:
                    for run in paragraph.runs:
                        run.font.name = '宋体'
                        run._element.rPr.rFonts.set(qn('w:eastAsia'), '宋体')
                        run.font.size = Pt(10)

        for i, row_data in enumerate(table_data):
            for j, cell_text in enumerate(row_data):
                if j < num_cols:
                    cell = table.rows[i].cells[j]
                    cell.text = cell_text
                    # 设置每个单元格的中文格式
                    for paragraph in cell.paragraphs:
                        for run in paragraph.runs:
                            run.font.name = '宋体'
                            run._element.rPr.rFonts.set(qn('w:eastAsia'), '宋体')
                            run.font.size = Pt(10)
                    if i == 0:  # 标题行
                        for paragraph in cell.paragraphs:
                            paragraph.runs[0].bold = True

    def _process_inline_formatting(self, text, paragraph, initial_run):
        """Process inline formatting (bold, italic) in a paragraph."""
        # 简单处理粗体
        if '**' in text:
            parts = text.split('**')
            paragraph.clear()
            for idx, part in enumerate(parts):
                if part:  # 跳过空字符串
                    if idx % 2 == 1:  # 奇数索引是粗体内容
                        run = paragraph.add_run(part)
                        run.bold = True
                    else:
                        run = paragraph.add_run(part)
                    run.font.name = '宋体'
                    run._element.rPr.rFonts.set(qn('w:eastAsia'), '宋体')
                    run.font.size = Pt(11)

    def convert_to_pdf(self, content):
        """Convert markdown to PDF using reportlab with academic formatting."""
        try:
            from reportlab.lib.pagesizes import A4
            from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
            from reportlab.lib.units import inch, cm
            from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, Table,
                                           TableStyle, PageBreak, PageTemplate, Frame)
            from reportlab.lib import colors
            from reportlab.pdfbase import pdfmetrics
            from reportlab.pdfbase.ttfonts import TTFont
            from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT
            from reportlab.platypus.flowables import Flowable
        except ImportError:
            print("Warning: reportlab not installed. Install with: pip install reportlab")
            return None

        output_path = self.output_dir / f"{self.base_name}.pdf"

        # === 设置文档页面 ===
        doc = SimpleDocTemplate(
            str(output_path),
            pagesize=A4,
            rightMargin=2.54*cm,
            leftMargin=2.54*cm,
            topMargin=2.54*cm,
            bottomMargin=1.91*cm
        )

        # === 注册中文字体 ===
        try:
            font_paths = {
                'SimSun': "C:/Windows/Fonts/simsun.ttc",      # 宋体
                'SimHei': "C:/Windows/Fonts/simhei.ttf",      # 黑体
                'MicrosoftYaHei': "C:/Windows/Fonts/msyh.ttc", # 微软雅黑
                'KaiTi': "C:/Windows/Fonts/simkai.ttf",      # 楷体
                'FangSong': "C:/Windows/Fonts/simfang.ttf"   # 仿宋
            }
            registered_fonts = []
            for font_name, font_path in font_paths.items():
                if os.path.exists(font_path):
                    try:
                        pdfmetrics.registerFont(TTFont(font_name, font_path))
                        registered_fonts.append(font_name)
                    except (OSError, IOError, RuntimeError):
                        continue
            if registered_fonts:
                print(f"已注册中文字体: {', '.join(registered_fonts)}")
        except Exception as e:
            print(f"注册中文字体时出错: {e}")

        # === 定义样式 ===
        styles = getSampleStyleSheet()

        # 使用宋体作为主要字体（检查已注册字体列表）
        registered_font_names = [f.name for f in pdfmetrics.fonts.values()] if hasattr(pdfmetrics, 'fonts') else []
        body_font = 'SimSun' if 'SimSun' in registered_font_names else 'Helvetica'
        heading_font = 'SimSun' if 'SimSun' in registered_font_names else 'Helvetica'

        # 标题样式
        title_style = ParagraphStyle(
            'AcademicTitle',
            parent=styles['Heading1'],
            fontName=heading_font,
            fontSize=18,
            textColor=colors.black,
            spaceBefore=12,
            spaceAfter=6,
            leading=24
        )

        # 二级标题样式
        heading2_style = ParagraphStyle(
            'AcademicHeading2',
            parent=styles['Heading2'],
            fontName=heading_font,
            fontSize=15,
            textColor=colors.black,
            spaceBefore=10,
            spaceAfter=6,
            leading=20
        )

        # 三级标题样式
        heading3_style = ParagraphStyle(
            'AcademicHeading3',
            parent=styles['Heading3'],
            fontName=heading_font,
            fontSize=13,
            textColor=colors.black,
            spaceBefore=8,
            spaceAfter=4,
            leading=18
        )

        # 正文样式 - 1.5倍行距
        body_style = ParagraphStyle(
            'AcademicBody',
            parent=styles['BodyText'],
            fontName=body_font,
            fontSize=11,
            leading=16.5,  # 1.5 * 11 = 16.5
            spaceBefore=0,
            spaceAfter=6,
            wordWrap='CJK'
        )

        # 引用块样式
        blockquote_style = ParagraphStyle(
            'Blockquote',
            parent=styles['BodyText'],
            fontName=body_font,
            fontSize=10,
            leading=15,
            spaceBefore=6,
            spaceAfter=6,
            leftIndent=0.75*inch,
            rightIndent=0.25*inch,
            textColor=colors.HexColor('#404040'),
            wordWrap='CJK'
        )

        # 参考文献样式
        bibliography_style = ParagraphStyle(
            'Bibliography',
            parent=styles['BodyText'],
            fontName=body_font,
            fontSize=10,
            leading=12,
            spaceBefore=3,
            spaceAfter=3,
            leftIndent=0.5*inch,
            firstLineIndent=-0.5*inch,
            wordWrap='CJK'
        )

        # 表格单元格样式
        table_cell_style = ParagraphStyle(
            'TableCell',
            parent=styles['BodyText'],
            fontName=body_font,
            fontSize=10,
            leading=14,
            wordWrap='CJK'
        )

        # 表格标题样式
        table_header_style = ParagraphStyle(
            'TableHeader',
            parent=styles['BodyText'],
            fontName=heading_font,
            fontSize=10,
            leading=14,
            wordWrap='CJK',
            textColor=colors.white
        )

        # === 解析内容 ===
        elements = []
        lines = content.split('\n')
        i = 0
        in_bibliography = False

        while i < len(lines):
            line = lines[i]

            if not line.strip():
                elements.append(Spacer(1, 0.1*inch))
                i += 1
            elif line.startswith('###'):
                in_bibliography = False
                text = line[3:].strip()
                elements.append(Paragraph(text, heading3_style))
                elements.append(Spacer(1, 0.05*inch))
                i += 1
            elif line.startswith('##'):
                in_bibliography = False
                text = line[2:].strip()
                elements.append(Paragraph(text, heading2_style))
                elements.append(Spacer(1, 0.08*inch))
                i += 1
            elif line.startswith('#'):
                in_bibliography = False
                text = line[1:].strip()
                elements.append(Paragraph(text, title_style))
                elements.append(Spacer(1, 0.1*inch))
                i += 1
            elif line.strip().startswith('>'):
                # Blockquote
                quote_text = line.strip()[1:].strip()
                elements.append(Paragraph(quote_text, blockquote_style))
                i += 1
            elif line.strip() == '---':
                elements.append(Spacer(1, 0.15*inch))
                i += 1
            # 检测表格
            elif '|' in line and i+1 < len(lines) and '|' in lines[i+1]:
                table_data = []
                while i < len(lines) and '|' in lines[i]:
                    row_line = lines[i]
                    if not re.match(r'^\s*\|[\s\-:]+\|$', row_line):
                        cells = [cell.strip() for cell in row_line.split('|')]
                        if cells and cells[0] == '':
                            cells = cells[1:]
                        if cells and cells[-1] == '':
                            cells = cells[:-1]
                        if cells:
                            table_data.append(cells)
                    i += 1

                if table_data and len(table_data) > 0:
                    num_cols = max(len(row) for row in table_data)
                    table_content = []
                    for row_idx, row in enumerate(table_data):
                        row_data = []
                        for cell_text in row:
                            formatted_text = cell_text.replace('**', '<b>').replace('*', '<i>')
                            if row_idx == 0:
                                row_data.append(Paragraph(formatted_text, table_header_style))
                            else:
                                row_data.append(Paragraph(formatted_text, table_cell_style))
                        while len(row_data) < num_cols:
                            row_data.append(Paragraph('', table_cell_style))
                        table_content.append(row_data)

                    table = Table(table_content, colWidths=None)
                    table_style = TableStyle([
                        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#4472C4')),
                        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                        ('FONTNAME', (0, 0), (-1, -1), body_font),
                        ('FONTSIZE', (0, 0), (-1, -1), 10),
                        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
                        ('TOPPADDING', (0, 0), (-1, -1), 8),
                        ('LEFTPADDING', (0, 0), (-1, -1), 6),
                        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
                        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f8f8f8')]),
                    ])
                    table.setStyle(table_style)
                    elements.append(table)
                    elements.append(Spacer(1, 0.1*inch))
            else:
                # 检测参考文献部分
                if line.strip().startswith('##') and '参考' in line:
                    in_bibliography = True
                    text = line[2:].strip()
                    elements.append(Paragraph(text, heading2_style))
                    elements.append(Spacer(1, 0.08*inch))
                    i += 1
                else:
                    # Handle basic formatting
                    text = line.replace('**', '<b>').replace('*', '<i>')
                    try:
                        if in_bibliography:
                            elements.append(Paragraph(text, bibliography_style))
                        else:
                            elements.append(Paragraph(text, body_style))
                    except (ValueError, AttributeError):
                        pass
                i += 1

        # === 构建PDF ===
        doc.build(elements)
        return output_path

    def convert_all(self):
        """Convert markdown to both PDF and Word formats."""
        content = self.read_markdown()

        print(f"Converting: {self.input_file.name}")
        print(f"Output directory: {self.output_dir}")
        print()

        # Convert to Word
        print("Creating Word document with academic formatting...")
        word_path = self.convert_to_word(content)
        if word_path:
            print(f"[OK] Word document created: {word_path}")

        # Convert to PDF
        print("Creating PDF document with academic formatting...")
        pdf_path = self.convert_to_pdf(content)
        if pdf_path:
            print(f"[OK] PDF document created: {pdf_path}")
        else:
            print("[ERROR] PDF conversion failed (reportlab not installed)")

        print()
        return word_path, pdf_path


def install_dependencies():
    """Install required Python packages."""
    import subprocess

    packages = [
        "markdown",
        "python-docx",
        "reportlab"
    ]

    print("Installing required packages...")
    for pkg in packages:
        print(f"  Installing {pkg}...")
        subprocess.check_call([sys.executable, "-m", "pip", "install", pkg])
    print("[OK] All packages installed successfully!")


def main():
    parser = argparse.ArgumentParser(description='Convert Markdown to PDF and Word - Academic Edition')
    parser.add_argument('input', nargs='?', help='Input markdown file')
    parser.add_argument('--output-dir', '-o', help='Output directory')
    parser.add_argument('--install-deps', action='store_true', help='Install required dependencies')
    parser.add_argument('--word-only', '-w', action='store_true', help='Convert to Word only')
    parser.add_argument('--pdf-only', '-p', action='store_true', help='Convert to PDF only')

    args = parser.parse_args()

    if args.install_deps:
        install_dependencies()
        return

    if not args.input:
        parser.print_help()
        return

    if not os.path.exists(args.input):
        print(f"Error: File not found: {args.input}")
        return

    converter = MarkdownConverter(args.input, args.output_dir)

    if args.word_only:
        content = converter.read_markdown()
        word_path = converter.convert_to_word(content)
        print(f"✓ Word document: {word_path}")
    elif args.pdf_only:
        content = converter.read_markdown()
        pdf_path = converter.convert_to_pdf(content)
        print(f"✓ PDF document: {pdf_path}")
    else:
        converter.convert_all()


if __name__ == "__main__":
    main()
